[workspace]
members = ["powercable","turbine", "charger", "transformer", "tickgen", "vehicle", "consumer", "fusion_reactor", "power_grid_factory"]
resolver = "2"

[workspace.package]
version = "0.0.1"
authors = ["AnnsAnn", "lukasseb"]
