services:
  mosquitto_broker:
    # MQTT Broker
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    ports:
      - "${MQTT_BROKER_PORT}:${MQTT_BROKER_PORT}" # MQTT port
    volumes:
      - ./mosquitto/config:/mosquitto/config # Configuration files
      - ./mosquitto/log:/mosquitto/log # Log files
      - ./mosquitto/data:/mosquitto/data # Data files
    networks:
      - mqtt_network
    restart: always

  dashboard:
    # Node-RED Dashboard
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: own_dashboard
    ports:
      - 127.0.0.1:${NODE_RED_PORT}:${NODE_RED_PORT} # Node-RED port
    volumes:
      - ./dashboard/data:/data # Node-RED data
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker

  tick_gen:
    build:
      context: ./tick_gen
      dockerfile: Dockerfile
    container_name: tick_gen
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker

  turbine:
    # Turbine Simulator
    build:
      context: .
      dockerfile: Dockerfile
    container_name: turbine
    command: ./turbine
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker

networks:
  mqtt_network:
    driver: bridge
