services:
  mosquitto_broker:
    # MQTT Broker
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    ports:
      - 1883:1883 # MQTT port
    volumes:
      - ./mosquitto/config:/mosquitto/config # Configuration files
      - ./mosquitto/log:/mosquitto/log # Log files
      - ./mosquitto/data:/mosquitto/data # Data files
    networks:
      - mqtt_network
    restart: always

  dashboard:
    # Node-RED Dashboard
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: own_dashboard
    ports:
      - 1880:1880 # Node-RED port
    volumes:
      - ./dashboard/data:/data # Node-RED data
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker

  tickgen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tickgen
    command: ./tickgen
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker

  transformer:
    # Transformer Simulator
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transformer
    command: ./transformer
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker

  turbine:
    # Turbine Simulator
    build:
      context: .
      dockerfile: Dockerfile
    command: ./turbine
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker
    deploy:
      replicas: 1
      mode: replicated

  charger:
    # Charger Simulator
    build:
      context: .
      dockerfile: Dockerfile
    command: ./charger
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker
    deploy:
      replicas: 3
      mode: replicated
  
  h0:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./consumer
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker
    environment:
      - CONSUMER_TYPE=H0
      - CONSUMER_NAME=Meier

  g3:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./consumer
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker
    environment:
      - CONSUMER_TYPE=G3
      - CONSUMER_NAME=Tesla

  g5:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./consumer
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker
    environment:
      - CONSUMER_TYPE=G5
      - CONSUMER_NAME=Backhus
    
networks:
  mqtt_network:
    driver: bridge
