services:
  mosquitto_broker:
    # MQTT Broker
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    ports:
      - 1883:1883 # MQTT port
    volumes:
      - ./mosquitto/config:/mosquitto/config # Configuration files
      - ./mosquitto/log:/mosquitto/log # Log files
      - ./mosquitto/data:/mosquitto/data # Data files
    networks:
      - mqtt_network
    restart: always

  dashboard:
    # Node-RED Dashboard
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: own_dashboard
    ports:
      - 1880:1880 # Node-RED port
    volumes:
      - ./dashboard/data:/data # Node-RED data
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker

  powergrid:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=full
    volumes:
      - ./.docker_data/logs:/app/logs
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker
    
networks:
  mqtt_network:
    driver: bridge
