services:
  mosquitto_broker:
    # MQTT Broker
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    ports:
      - 1883:1883 # MQTT port
    volumes:
      - ./mosquitto/config:/mosquitto/config # Configuration files
      - ./mosquitto/log:/mosquitto/log # Log files
      - ./mosquitto/data:/mosquitto/data # Data files
    networks:
      - mqtt_network
    restart: always

  dashboard:
    # Node-RED Dashboard
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: own_dashboard
    ports:
      - 1880:1880 # Node-RED port
    volumes:
      - ./dashboard/data:/data # Node-RED data
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker

  tickgen:
    image: local/powergrid:latest
    command: ./tickgen
    volumes:
      - ./.docker_data/logs:/app/logs
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker

  transformer:
    # Transformer Simulator
    image: local/powergrid:latest
    command: ./transformer
    volumes:
      - ./.docker_data/logs:/app/logs
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker

  fusion_reactor:
    image: local/powergrid:latest
    command: ./fusion_reactor
    volumes:
      - ./.docker_data/logs:/app/logs
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker

  turbine:
    # Turbine Simulator
    image: local/powergrid:latest
    command: ./turbine
    volumes:
      - ./.docker_data/Wind:/app/Wind
      - ./.docker_data/AirTemperature:/app/AirTemperature
      - ./.docker_data/logs:/app/logs
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker
    deploy:
      replicas: 8
      mode: replicated

  charger:
    # Charger Simulator
    image: local/powergrid:latest
    command: ./charger
    volumes:
      - ./.docker_data/logs:/app/logs
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker
    deploy:
      replicas: 4
      mode: replicated

  vehicle:
    # Vehicle Simulator
    image: local/powergrid:latest
    command: ./vehicle
    volumes:
      - ./.docker_data/logs:/app/logs
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker
    deploy:
      replicas: 2
      mode: replicated

  haushalt:
    image: local/powergrid:latest
    command: ./consumer
    volumes:
      - ./.docker_data/logs:/app/logs
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker
    environment:
      - CONSUMER_TYPE=H

  gewerbe:
    image: local/powergrid:latest
    command: ./consumer
    volumes:
      - ./.docker_data/logs:/app/logs
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker
    environment:
      - CONSUMER_TYPE=G

  bauernhof:
    image: local/powergrid:latest
    command: ./consumer
    volumes:
      - ./.docker_data/logs:/app/logs
    networks:
      - mqtt_network
    depends_on:
      - mosquitto_broker
    environment:
      - CONSUMER_TYPE=L
    
networks:
  mqtt_network:
    driver: bridge
