[package]
name = "vehicle"
edition = "2024"
version.workspace = true
authors.workspace = true

[dependencies]
bytes = "1.10.1"
env_logger = "0.11.8"
log = "0.4.27"
powercable = { path = "../powercable" }
rand = "0.9.1"
rumqttc = "0.24.0"
serde_json = "1.0.140"
tokio = "1.45.0"
