[package]
name = "vehicle"
edition = "2021"
version.workspace = true
authors.workspace = true

[dependencies]
bytes = "1.10.1"
tracing = "0.1"
powercable = { path = "../powercable" }
rand = "0.9.1"
rumqttc = "0.24.0"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = "1.45.0"
